export type Phase = {
  id: number;
  title: string;
  area: string;
  summary: string;
  scope: string[];
  evidence: string;
  course?: string;
  courseTitle?: string;
  course2?: string;
  course2Title?: string;
};

export type SprintDay = {
  day: number;
  title: string;
  phase: string;
  sessions: [string, string, string, string];
};

export const phases: Phase[] = [
  {
    id: 1,
    title: 'System Design Foundations',
    area: 'Architecture',
    summary: 'نظرة أولى على بنية تطبيقات الويب والخدمات: كيف ينتقل الطلب من العميل إلى الـAPI وقاعدة البيانات، وكيف تتغير البنية عند التوسع.',
    scope: ['Client–Server model', 'Single-server architecture', 'SQL vs NoSQL', 'Vertical vs horizontal scaling', 'Load balancers & health checks', 'REST & GraphQL overview', 'Authentication vs authorization'],
    evidence: 'Architecture diagram يوضح Request Flow من العميل إلى الـAPI وقاعدة البيانات، مع تحديد نقاط التوسع الأساسية.',
    course: 'https://www.youtube.com/watch?v=C842vFY5kRo',
    courseTitle: 'System Design Course — freeCodeCamp (2026)',
  },
  {
    id: 2,
    title: 'JavaScript Fundamentals',
    area: 'Language',
    summary: 'تثبيت أساس JavaScript المطلوب لفهم Node.js وكتابة منطق التطبيق بدون الاعتماد على framework.',
    scope: ['Variables & data types', 'Conditions & loops', 'Functions', 'Arrays & array methods', 'Objects & destructuring', 'Scope & closures', 'Promises & async/await', 'Error handling'],
    evidence: 'تمارين JavaScript + mini application مكتوبة بدون framework، مع القدرة على شرح الكود وإعادة كتابة الأجزاء الأساسية.',
    course: 'https://www.youtube.com/watch?v=jS4aFq5-91M',
    courseTitle: 'JavaScript Programming — Full Course',
  },
  {
    id: 3,
    title: 'TypeScript',
    area: 'Primary Language',
    summary: 'استخدام TypeScript كلغة المسار الأساسية وكتابة كود typed واضح قبل الدخول في NestJS.',
    scope: ['Type inference', 'Interfaces & type aliases', 'Union types', 'Narrowing', 'Generics', 'Utility types', 'Function return types', 'Typed async code'],
    evidence: 'تحويل مشروع JavaScript سابق إلى TypeScript مع typing واضح للأجزاء الرئيسية وإزالة الأنواع غير الضرورية.',
    course: 'https://www.youtube.com/watch?v=SpwzRDUQ1GI',
    courseTitle: 'Learn TypeScript — Full Course',
  },
  {
    id: 4,
    title: 'Git & GitHub Workflow',
    area: 'Version Control',
    summary: 'إدارة التغييرات والفروع والـhistory بشكل منظم لكل مشروع في المسار.',
    scope: ['add / commit / push', 'Clone & remote repositories', 'Branches', 'Merge workflow', 'Conflict resolution', 'Undo & recovery basics', 'Repository structure', 'README'],
    evidence: 'Repository يحتوي feature branch وmerge واضح وcommits مرتبة وREADME يشرح المشروع وتشغيله.',
    course: 'https://www.youtube.com/watch?v=RGOj5yH7evk',
    courseTitle: 'Git and GitHub for Beginners',
  },
  {
    id: 5,
    title: 'Node.js, HTTP & Express',
    area: 'Runtime & APIs',
    summary: 'فهم Node.js وHTTP قبل استخدام NestJS، ثم بناء REST APIs مباشرة باستخدام Express.',
    scope: ['Node runtime', 'Modules & npm', 'Filesystem', 'Environment variables', 'HTTP request / response lifecycle', 'Event loop', 'Promises & async code', 'Events & streams basics', 'Express routing', 'Middleware', 'REST conventions', 'HTTP status codes'],
    evidence: 'REST API منظمة إلى routes/controllers/services مع validation وerror handling وPostman collection.',
    course: 'https://www.youtube.com/watch?v=Oe421EPjeBE',
    courseTitle: 'Node.js and Express.js — Full Course',
  },
  {
    id: 6,
    title: 'Node.js Backend Projects',
    area: 'Applied Backend',
    summary: 'تطبيق نفس أساسيات Node.js وExpress على عدة APIs قبل الانتقال إلى framework أعلى.',
    scope: ['Task Manager API', 'Store API', 'JWT Basics', 'Jobs API', 'CRUD', 'Filtering & pagination', 'Authentication', 'Protected routes', 'Ownership rules', 'Validation & error handling'],
    evidence: 'أربعة APIs قابلة للتشغيل ومرفوعة على GitHub، مع القدرة على إعادة بناء الـauth والـCRUD بدون الرجوع للكود خطوة بخطوة.',
    course: 'https://www.youtube.com/watch?v=qwfE7fSVaZM',
    courseTitle: 'Node.js / Express — Build 4 Projects',
  },
  {
    id: 7,
    title: 'SQL & PostgreSQL',
    area: 'Databases',
    summary: 'تعلم SQL ونمذجة البيانات مباشرة قبل استخدام ORM حتى تكون عمليات القراءة والكتابة والعلاقات مفهومة.',
    scope: ['Tables & constraints', 'SELECT / INSERT / UPDATE / DELETE', 'WHERE / ORDER BY / LIMIT', 'Primary & foreign keys', 'Relationships', 'JOINs', 'GROUP BY / HAVING', 'Indexes', 'Transactions & ACID', 'Normalization', 'UUID'],
    evidence: 'ERD لنظام حجز + قاعدة PostgreSQL فعلية + مجموعة queries يدوية تشمل joins وaggregations وtransactions.',
    course: 'https://www.youtube.com/watch?v=qw--VYLpxG4',
    courseTitle: 'PostgreSQL Full Course',
  },
  {
    id: 8,
    title: 'NestJS Production Backend',
    area: 'Core Backend Stack',
    summary: 'بناء Backend منظم باستخدام NestJS وPrisma وPostgreSQL، مع authentication وصلاحيات وتوثيق API.',
    scope: ['Modules / controllers / services', 'Dependency injection', 'DTOs & ValidationPipe', 'Prisma schema & migrations', 'PostgreSQL relations', 'JWT authentication', 'Refresh tokens', 'Authorization & RBAC', 'Guards', 'CORS & rate limiting', 'Swagger / OpenAPI', 'Users / products / cart / orders / payments'],
    evidence: 'E-commerce backend كامل مع Auth وRBAC وPrisma/PostgreSQL وSwagger، والقدرة على شرح structure وrequest flow لكل module.',
    course: 'https://www.youtube.com/watch?v=RjMvgpeoSuw',
    courseTitle: 'NestJS Full Course 2026 — Production E-Commerce',
  },
  {
    id: 9,
    title: 'Redis & Caching',
    area: 'Performance',
    summary: 'استخدام Redis للبيانات سريعة الوصول والـcaching بعد فهم قاعدة البيانات الدائمة.',
    scope: ['Strings', 'Hashes', 'Lists', 'Sets', 'TTL', 'Caching patterns', 'Cache invalidation', 'Transactions basics', 'Pub/Sub basics', 'Security basics'],
    evidence: 'إضافة Redis cache إلى endpoint فعلي في NestJS مع TTL وinvalidation واضحين وقياس الفرق في القراءة.',
    course: 'https://www.youtube.com/watch?v=XCsS_NVAa1g',
    courseTitle: 'Redis Course — freeCodeCamp',
  },
  {
    id: 10,
    title: 'Queues & Background Jobs',
    area: 'Async Processing',
    summary: 'نقل الأعمال غير الفورية خارج HTTP request باستخدام BullMQ وRedis وworkers.',
    scope: ['@nestjs/bullmq', 'Queues & workers', 'Producer / processor flow', 'Events & listeners', 'Retries', 'Delayed jobs', 'Failure handling', 'Idempotency basics'],
    evidence: 'Background job حقيقي لإرسال Email/Notification أو processing task مع retry وfailure handling.',
    course: 'https://www.youtube.com/watch?v=BkaNpM7CqWM',
    courseTitle: 'NestJS + BullMQ — Event-Driven Queues',
  },
  {
    id: 11,
    title: 'WebSockets & Real-Time',
    area: 'Realtime Systems',
    summary: 'بناء اتصال ثنائي الاتجاه للأحداث الفورية بدل الاعتماد على request/response فقط.',
    scope: ['NestJS gateways', 'Socket.IO', 'Connection lifecycle', 'Events', 'Rooms', 'Realtime notifications', 'Socket authentication'],
    evidence: 'Chat أو notification service بسيط يعمل لحظيًا مع user identification وصلاحيات واضحة.',
    course: 'https://www.youtube.com/watch?v=atbdpX4CViM',
    courseTitle: 'WebSockets with NestJS + Socket.IO',
  },
  {
    id: 12,
    title: 'Backend Testing',
    area: 'Testing',
    summary: 'اختبار منطق التطبيق وواجهات HTTP على أكثر من مستوى بدل الاعتماد على الاختبار اليدوي.',
    scope: ['Jest', 'Unit tests', 'Mocks', 'Service tests', 'Controller tests', 'Integration tests', 'E2E with Supertest', 'Test database strategy', 'Coverage basics'],
    evidence: 'Test suite لمشروع NestJS تغطي Auth وService logic وHTTP E2E لحالات النجاح والفشل.',
    course: 'https://www.youtube.com/watch?v=GSoGVlG1MTQ&list=PLIGDNOJWiL1-8hpXEDlD1UrphjmZ9aMT1',
    courseTitle: 'NestJS Testing — Unit & E2E Playlist',
  },
  {
    id: 13,
    title: 'Linux Fundamentals',
    area: 'Server Environment',
    summary: 'استخدام بيئة Linux التي سيعمل عليها الـBackend وفهم الملفات والعمليات والشبكة والسجلات.',
    scope: ['Terminal navigation', 'Files & directories', 'Permissions basics', 'Processes', 'Package managers', 'Environment variables', 'Networking basics', 'Logs', 'Common shell commands'],
    evidence: 'تشغيل Backend من terminal وإدارة process وenvironment variables وlogs بدون واجهة رسومية.',
    course: 'https://www.youtube.com/watch?v=ROjZy1WbCIA',
    courseTitle: 'Linux Operating System — Crash Course',
  },
  {
    id: 14,
    title: 'Docker & Docker Compose',
    area: 'Containers',
    summary: 'تغليف التطبيق وخدماته في containers قابلة للتشغيل بنفس الإعدادات محليًا وفي CI وعلى السيرفر.',
    scope: ['Images & containers', 'Docker commands', 'Dockerfile', 'Volumes', 'Networks', 'Docker Compose', 'Registry basics', 'Production image practices'],
    evidence: 'تشغيل NestJS + PostgreSQL + Redis كاملًا باستخدام Docker Compose من أمر واحد.',
    course: 'https://www.youtube.com/watch?v=3c-iBn73dDE',
    courseTitle: 'Docker Full Course — TechWorld with Nana',
  },
  {
    id: 15,
    title: 'CI/CD with GitHub Actions',
    area: 'CI/CD',
    summary: 'تشغيل الاختبارات والبناء وخطوات النشر تلقائيًا مع كل تغيير مناسب في المستودع.',
    scope: ['Actions events', 'Workflows', 'Jobs & steps', 'Runners', 'Secrets', 'Install → test → build', 'Docker image pipeline', 'Deployment gates'],
    evidence: 'GitHub Actions workflow يشغل install/test/build تلقائيًا ويمنع نشر build فاشل.',
    course: 'https://www.youtube.com/watch?v=R8_veQiYBjI',
    courseTitle: 'GitHub Actions CI/CD Tutorial',
  },
  {
    id: 16,
    title: 'AWS Deployment',
    area: 'Cloud',
    summary: 'نشر الـBackend وخدماته الأساسية على AWS وفهم الصلاحيات والشبكة والمراقبة.',
    scope: ['IAM', 'EC2', 'S3', 'RDS', 'Networking basics', 'Security Groups', 'CloudWatch', 'Deployment', 'Health checks', 'Logging & monitoring'],
    evidence: 'Backend منشور على AWS مع database وhealth endpoint وCloudWatch logs وخطوات نشر موثقة.',
    course: 'https://www.youtube.com/watch?v=YC9ZxTotkxk',
    courseTitle: 'AWS Full Course for Beginners',
    course2: 'https://explore.skillbuilder.aws/learn/courses/134/aws-cloud-practitioner-essentials',
    course2Title: 'AWS Cloud Practitioner Essentials — Official',
  },
  {
    id: 17,
    title: 'SOLID & Refactoring',
    area: 'Code Design',
    summary: 'مراجعة تصميم الكود وتحسين حدود المسؤوليات والاعتماديات داخل مشروع Backend موجود.',
    scope: ['Single Responsibility Principle', 'Open/Closed Principle', 'Liskov Substitution Principle', 'Interface Segregation Principle', 'Dependency Inversion Principle', 'Code smells', 'Refactoring decisions'],
    evidence: 'Refactor لخدمة موجودة مع before/after وشرح المشكلة التي عالجها كل تغيير.',
    course: 'https://www.youtube.com/watch?v=eHjNjyvZBto',
    courseTitle: 'SOLID Principles with TypeScript',
  },
  {
    id: 18,
    title: 'Clean Architecture',
    area: 'Architecture',
    summary: 'فصل business logic عن framework وقاعدة البيانات وتحديد اتجاه واضح للاعتماديات.',
    scope: ['Domain layer', 'Application / use cases', 'Infrastructure layer', 'Dependency direction', 'Repository abstraction', 'Framework as implementation detail'],
    evidence: 'إعادة تصميم NestJS module واحد بطبقات واضحة مع dependency diagram وrepository abstraction.',
    course: 'https://www.youtube.com/watch?v=UMUJ2-w9LIM',
    courseTitle: 'Clean Architecture with TypeScript — Series',
  },
  {
    id: 19,
    title: 'System Design — Applied Pass',
    area: 'System Design',
    summary: 'إعادة دراسة System Design بعد تطبيق PostgreSQL وRedis وQueues وDocker وAWS وربط كل مفهوم بحالة استخدام فعلية.',
    scope: ['Caching strategy', 'Queues', 'Database scaling', 'Load balancing', 'Single points of failure', 'Consistency trade-offs', 'Rate limiting', 'Observability', 'Designing for failure'],
    evidence: 'System design لنظام Booking أو Notifications مع diagram وكتابة القرارات والـtrade-offs بوضوح.',
    course: 'https://www.youtube.com/watch?v=C842vFY5kRo',
    courseTitle: 'System Design Course — Second Pass',
  },
  {
    id: 20,
    title: 'Capstone Backend Project',
    area: 'Capstone',
    summary: 'بناء Backend مستقل بدون tutorial خطوة بخطوة، من تحديد المتطلبات حتى الاختبارات والنشر.',
    scope: ['Requirements & scope', 'ERD & API contract', 'NestJS + Prisma + PostgreSQL', 'JWT & RBAC', 'Redis', 'BullMQ', 'WebSockets', 'Jest & E2E', 'Docker Compose', 'GitHub Actions', 'AWS deployment', 'Logging & observability', 'Technical documentation'],
    evidence: 'مشروع Backend منشور فعليًا مع README وarchitecture diagram وAPI documentation وCI/CD واختبارات قابلة للتشغيل.',
  },
];

export const sprintDays: SprintDay[] = [
  {day:1,title:'System Design Overview + JavaScript Intro',phase:'01–02',sessions:['System Design: request flow, databases, scaling & load balancing','JavaScript: variables, types & operators','Conditions, loops & functions','Request-flow diagram + JavaScript exercises']},
  {day:2,title:'JavaScript Core',phase:'02',sessions:['Arrays & methods','Objects & destructuring','Functions, scope & closures','Exercises without returning to the video']},
  {day:3,title:'JavaScript Async + Mini Project',phase:'02',sessions:['Promises & async/await','Error handling + modules + npm','Mini project implementation','Rebuild the project from memory']},
  {day:4,title:'TypeScript Core',phase:'03',sessions:['Types & inference','Interfaces & type aliases','Unions & narrowing','Convert the JavaScript project to TypeScript']},
  {day:5,title:'TypeScript Advanced + Git',phase:'03–04',sessions:['Generics & utility types','Typed async code','Git commits & history','Remote repository + README']},
  {day:6,title:'Git Workflow + Node.js Intro',phase:'04–05',sessions:['Branches, merge & conflicts','Git workflow challenge','Node runtime, modules & npm','Filesystem, env & HTTP basics']},
  {day:7,title:'Node.js Internals',phase:'05',sessions:['Event loop & async model','Events & streams basics','Manual HTTP server','Node exercises from scratch']},
  {day:8,title:'Express + REST APIs',phase:'05',sessions:['Express routes & middleware','Params, query, body & status codes','Validation + error middleware','REST API + Postman collection']},
  {day:9,title:'Task Manager API',phase:'06',sessions:['Data model + endpoints','CRUD implementation','Validation + error handling','README + tests + push']},
  {day:10,title:'Store API',phase:'06',sessions:['Products API','Filtering & sorting','Pagination & search','Refactor + Postman + push']},
  {day:11,title:'JWT Authentication',phase:'06',sessions:['Register + password hashing','Login + JWT','Protected routes','Rebuild the auth flow']},
  {day:12,title:'Jobs API',phase:'06',sessions:['Auth + ownership rules','Jobs CRUD','Error handling cleanup','Node/Express review']},
  {day:13,title:'SQL Foundations',phase:'07',sessions:['Tables + constraints','CRUD SQL','WHERE / ORDER / LIMIT','30 manual SQL queries']},
  {day:14,title:'SQL Relationships',phase:'07',sessions:['Primary/foreign keys + relationships','JOINs','GROUP BY + HAVING','Booking-system ERD']},
  {day:15,title:'PostgreSQL',phase:'07',sessions:['Indexes','Transactions + ACID','Normalization','Database mini project + query review']},
  {day:16,title:'NestJS Core',phase:'08',sessions:['Modules + controllers','Services + dependency injection','DTOs + ValidationPipe','First CRUD module']},
  {day:17,title:'NestJS + Prisma',phase:'08',sessions:['Prisma schema + migrations','Relations + queries','Config + application structure','Complete resource module']},
  {day:18,title:'Authentication, RBAC & Security',phase:'08',sessions:['Register/login + hashing','JWT + refresh token flow','Guards + roles + permissions','CORS, rate limiting + Swagger']},
  {day:19,title:'NestJS Project — Core Modules',phase:'08',sessions:['Users + auth architecture','Products + categories','Validation + errors','API documentation + review']},
  {day:20,title:'NestJS Project — Orders & Payments',phase:'08',sessions:['Cart + orders','Transactions + business rules','Payments flow','Repository cleanup + push']},
  {day:21,title:'Redis & Caching',phase:'09',sessions:['Redis data types + TTL','Caching patterns','Cache invalidation','Integrate Redis into NestJS']},
  {day:22,title:'Queues & Background Jobs',phase:'10',sessions:['BullMQ architecture','Producer + worker','Retries + delayed jobs','Email/notification background job']},
  {day:23,title:'WebSockets & Real-Time',phase:'11',sessions:['NestJS gateway','Socket.IO lifecycle','Rooms + socket auth','Realtime chat/notifications']},
  {day:24,title:'Backend Testing',phase:'12',sessions:['Jest unit tests','Mocks + service tests','Integration tests','E2E with Supertest']},
  {day:25,title:'Linux Fundamentals',phase:'13',sessions:['Filesystem + permissions','Processes + packages','Networking + env','Run and inspect the backend from terminal']},
  {day:26,title:'Docker & Docker Compose',phase:'14',sessions:['Images + containers','Dockerfile','Volumes + networks','NestJS + PostgreSQL + Redis Compose']},
  {day:27,title:'GitHub Actions & CI/CD',phase:'15',sessions:['Workflow structure','Secrets + triggers','Install → test → build pipeline','Deployment gate + verification']},
  {day:28,title:'AWS Deployment',phase:'16',sessions:['IAM + EC2','RDS + S3','Networking + Security Groups','Deploy + CloudWatch + health checks']},
  {day:29,title:'SOLID + Clean Architecture',phase:'17–18',sessions:['SOLID principles','Refactor an existing service','Clean Architecture layers','Refactor one NestJS module + diagram']},
  {day:30,title:'System Design + Capstone Planning',phase:'19–20',sessions:['System Design second pass','Design a production system','Capstone scope + ERD + API contract','Create repo, milestones & implementation plan']},
];

export const sessionTimes = ['08:00–10:30', '11:00–13:30', '14:30–17:00', '17:30–20:00'];
export const breaks = ['10:30–11:00 · Break', '13:30–14:30 · Lunch / Prayer', '17:00–17:30 · Break'];
