export type Phase = {
  id: number;
  title: string;
  area: string;
  summary: string;
  scope: string[];
  evidence: string;
  course?: string;
  courseTitle?: string;
  course2?: string;
  course2Title?: string;
};

export type SprintDay = {
  day: number;
  title: string;
  phase: string;
  sessions: [string, string, string, string];
};

export const phases: Phase[] = [
  {
    id: 1,
    title: 'System Design Foundations',
    area: 'Architecture',
    summary: 'نظرة أولى على بنية تطبيقات الويب والخدمات: كيف ينتقل الطلب من العميل إلى الـAPI وقاعدة البيانات، وكيف تتغير البنية عند التوسع.',
    scope: ['Client–Server model', 'Single-server architecture', 'SQL vs NoSQL', 'Vertical vs horizontal scaling', 'Load balancers & health checks', 'REST & GraphQL overview', 'Authentication vs authorization'],
    evidence: 'Architecture diagram يوضح Request Flow من العميل إلى الـAPI وقاعدة البيانات، مع تحديد نقاط التوسع الأساسية.',
    course: 'https://www.youtube.com/watch?v=C842vFY5kRo',
    courseTitle: 'System Design Course — freeCodeCamp (2026)',
  },
  {
    id: 2,
    title: 'JavaScript Fundamentals',
    area: 'Language',
    summary: 'تثبيت أساس JavaScript المطلوب لفهم Node.js وكتابة منطق التطبيق بدون الاعتماد على framework.',
    scope: ['Variables & data types', 'Conditions & loops', 'Functions', 'Arrays & array methods', 'Objects & destructuring', 'Scope & closures', 'Promises & async/await', 'Error handling'],
    evidence: 'تمارين JavaScript + mini application مكتوبة بدون framework، مع القدرة على شرح الكود وإعادة كتابة الأجزاء الأساسية.',
    course: 'https://www.youtube.com/watch?v=jS4aFq5-91M',
    courseTitle: 'JavaScript Programming — Full Course',
  },
  {
    id: 3,
    title: 'TypeScript',
    area: 'Primary Language',
    summary: 'استخدام TypeScript كلغة المسار الأساسية وكتابة كود typed واضح قبل الدخول في NestJS.',
    scope: ['Type inference', 'Interfaces & type aliases', 'Union types', 'Narrowing', 'Generics', 'Utility types', 'Function return types', 'Typed async code'],
    evidence: 'تحويل مشروع JavaScript سابق إلى TypeScript مع typing واضح للأجزاء الرئيسية وإزالة الأنواع غير الضرورية.',
    course: 'https://www.youtube.com/watch?v=SpwzRDUQ1GI',
    courseTitle: 'Learn TypeScript — Full Course',
  },
  {
    id: 4,
    title: 'Git & GitHub Workflow',
    area: 'Version Control',
    summary: 'إدارة التغييرات والفروع والـhistory بشكل منظم لكل مشروع في المسار.',
    scope: ['add / commit / push', 'Clone & remote repositories', 'Branches', 'Merge workflow', 'Conflict resolution', 'Undo & recovery basics', 'Repository structure', 'README'],
    evidence: 'Repository يحتوي feature branch وmerge واضح وcommits مرتبة وREADME يشرح المشروع وتشغيله.',
    course: 'https://www.youtube.com/watch?v=RGOj5yH7evk',
    courseTitle: 'Git and GitHub for Beginners',
  },
  {
    id: 5,
    title: 'Node.js, HTTP, REST & Express',
    area: 'Runtime & APIs',
    summary: 'فهم Node.js وHTTP بعمق كافٍ لبناء REST APIs صحيحة قبل الانتقال إلى NestJS.',
    scope: ['Node runtime', 'Modules & npm', 'Environment variables', 'HTTP request / response lifecycle', 'Headers & cookies', 'HTTP methods & status codes', 'Event loop', 'Events & streams basics', 'Express routing & middleware', 'REST conventions', 'Validation', 'Centralized error handling', 'Pagination', 'Filtering & sorting', 'File uploads basics'],
    evidence: 'REST API منظمة إلى routes/controllers/services مع validation وerror handling وpagination/filtering وPostman collection.',
    course: 'https://www.youtube.com/watch?v=Oe421EPjeBE',
    courseTitle: 'Node.js and Express.js — Full Course',
  },
  {
    id: 6,
    title: 'Node.js Backend Projects',
    area: 'Applied Backend',
    summary: 'تطبيق أساسيات Node.js وExpress على عدة APIs قبل الانتقال إلى framework أعلى.',
    scope: ['Task Manager API', 'Store API', 'JWT Basics', 'Jobs API', 'CRUD', 'Filtering & pagination', 'Authentication', 'Protected routes', 'Ownership rules', 'Validation & error handling'],
    evidence: 'أربعة APIs قابلة للتشغيل ومرفوعة على GitHub، مع القدرة على إعادة بناء الـauth والـCRUD بدون الرجوع للكود خطوة بخطوة.',
    course: 'https://www.youtube.com/watch?v=qwfE7fSVaZM',
    courseTitle: 'Node.js / Express — Build 4 Projects',
  },
  {
    id: 7,
    title: 'SQL, PostgreSQL & Database Design',
    area: 'Databases',
    summary: 'تعلم SQL وتصميم قواعد البيانات وفهم الأداء والمعاملات قبل الاعتماد على ORM.',
    scope: ['Tables & constraints', 'CRUD SQL', 'Primary & foreign keys', 'Relationships & ERD', 'JOINs', 'GROUP BY / HAVING', 'Normalization', 'Transactions & ACID', 'Indexes', 'Query plans / EXPLAIN basics', 'Migrations', 'Locking & concurrency basics', 'N+1 problem', 'Connection pooling', 'UUID'],
    evidence: 'ERD لنظام حجز + PostgreSQL فعلية + queries يدوية تشمل joins وaggregations وtransactions + تحليل query plan واحد على الأقل.',
    course: 'https://www.youtube.com/watch?v=qw--VYLpxG4',
    courseTitle: 'PostgreSQL Full Course',
  },
  {
    id: 8,
    title: 'NestJS Production Backend',
    area: 'Core Backend Stack',
    summary: 'بناء Backend منظم باستخدام NestJS وPrisma وPostgreSQL مع authentication وصلاحيات وتوثيق API وقواعد عمل حقيقية.',
    scope: ['Modules / controllers / services', 'Dependency injection', 'DTOs & ValidationPipe', 'Prisma schema & migrations', 'PostgreSQL relations', 'JWT authentication', 'Refresh tokens', 'Authorization & RBAC', 'Guards', 'Configuration management', 'Swagger / OpenAPI', 'Error handling', 'Business rules', 'Users / products / cart / orders / payments'],
    evidence: 'E-commerce backend كامل مع Auth وRBAC وPrisma/PostgreSQL وSwagger، والقدرة على شرح structure وrequest flow والـbusiness rules لكل module.',
    course: 'https://www.youtube.com/watch?v=RjMvgpeoSuw',
    courseTitle: 'NestJS Full Course 2026 — Production E-Commerce',
  },
  {
    id: 9,
    title: 'Backend Security & API Hardening',
    area: 'Application Security',
    summary: 'تقوية الـBackend ضد أكثر أخطاء الـAPI شيوعًا وتطبيق الحماية كجزء من التصميم وليس كإضافة أخيرة.',
    scope: ['Password hashing', 'JWT security', 'Refresh-token rotation', 'Authentication vs authorization', 'RBAC & permissions', 'CORS', 'CSRF concepts', 'XSS concepts', 'SQL injection prevention', 'Rate limiting', 'Helmet / security headers', 'Secrets management', 'Input validation & sanitization', 'OWASP API Security Top 10', 'Idempotency for sensitive operations'],
    evidence: 'Security hardening لمشروع NestJS قائم مع checklist واضحة، protected endpoints، rate limiting، secure headers، validation، token strategy واختبارات لحالات authorization الفاشلة.',
    course: 'https://docs.nestjs.com/security/authentication',
    courseTitle: 'NestJS Security — Authentication',
    course2: 'https://owasp.org/API-Security/editions/2023/en/0x11-t10/',
    course2Title: 'OWASP API Security Top 10 — 2023',
  },
  {
    id: 10,
    title: 'Redis & Caching',
    area: 'Performance',
    summary: 'استخدام Redis للبيانات سريعة الوصول والـcaching بعد فهم قاعدة البيانات الدائمة.',
    scope: ['Strings', 'Hashes', 'Lists', 'Sets', 'TTL', 'Caching patterns', 'Cache invalidation', 'Transactions basics', 'Pub/Sub basics', 'Security basics'],
    evidence: 'إضافة Redis cache إلى endpoint فعلي في NestJS مع TTL وinvalidation واضحين وقياس الفرق في القراءة.',
    course: 'https://www.youtube.com/watch?v=XCsS_NVAa1g',
    courseTitle: 'Redis Course — freeCodeCamp',
  },
  {
    id: 11,
    title: 'Queues & Background Jobs',
    area: 'Async Processing',
    summary: 'نقل الأعمال غير الفورية خارج HTTP request باستخدام BullMQ وRedis وworkers.',
    scope: ['@nestjs/bullmq', 'Queues & workers', 'Producer / processor flow', 'Events & listeners', 'Retries', 'Delayed jobs', 'Failure handling', 'Failed/dead jobs', 'Idempotency'],
    evidence: 'Background job حقيقي لإرسال Email/Notification أو processing task مع retries وfailure handling ومنع التنفيذ المكرر.',
    course: 'https://www.youtube.com/watch?v=BkaNpM7CqWM',
    courseTitle: 'NestJS + BullMQ — Event-Driven Queues',
  },
  {
    id: 12,
    title: 'WebSockets & Real-Time',
    area: 'Realtime Systems',
    summary: 'بناء اتصال ثنائي الاتجاه للأحداث الفورية بدل الاعتماد على request/response فقط.',
    scope: ['NestJS gateways', 'Socket.IO', 'Connection lifecycle', 'Events', 'Rooms', 'Realtime notifications', 'Socket authentication'],
    evidence: 'Chat أو notification service بسيط يعمل لحظيًا مع user identification وصلاحيات واضحة.',
    course: 'https://www.youtube.com/watch?v=atbdpX4CViM',
    courseTitle: 'WebSockets with NestJS + Socket.IO',
  },
  {
    id: 13,
    title: 'Backend Testing',
    area: 'Testing',
    summary: 'اختبار منطق التطبيق وواجهات HTTP على أكثر من مستوى بدل الاعتماد على الاختبار اليدوي.',
    scope: ['Jest', 'Unit tests', 'Mocks', 'Service tests', 'Controller tests', 'Integration tests', 'E2E with Supertest', 'Test database strategy', 'Coverage basics'],
    evidence: 'Test suite لمشروع NestJS تغطي Auth وService logic وHTTP E2E لحالات النجاح والفشل.',
    course: 'https://www.youtube.com/watch?v=GSoGVlG1MTQ&list=PLIGDNOJWiL1-8hpXEDlD1UrphjmZ9aMT1',
    courseTitle: 'NestJS Testing — Unit & E2E Playlist',
  },
  {
    id: 14,
    title: 'Logging, Monitoring & Observability',
    area: 'Observability',
    summary: 'معرفة ما يحدث داخل النظام في الإنتاج: تتبع الطلبات والأخطاء والبطء وصحة الخدمات بدل التخمين عند حدوث مشكلة.',
    scope: ['Structured logging', 'Log levels', 'Request / correlation IDs', 'Centralized error tracking', 'Health checks', 'Metrics', 'Latency & error-rate signals', 'Tracing basics', 'OpenTelemetry fundamentals', 'Monitoring dashboards', 'Alerts', 'Observability vs monitoring'],
    evidence: 'إضافة structured logs وrequest IDs وhealth endpoint وmetrics/tracing إلى Backend فعلي، ثم تتبع request بطيء أو خطأ من البداية للنهاية.',
    course: 'https://training.linuxfoundation.org/training/getting-started-with-opentelemetry-lfs148/',
    courseTitle: 'Linux Foundation LFS148 — Getting Started with OpenTelemetry',
    course2: 'https://opentelemetry.io/docs/languages/js/getting-started/nodejs/',
    course2Title: 'OpenTelemetry Node.js — Hands-on Guide',
  },
  {
    id: 15,
    title: 'Linux & Server Fundamentals',
    area: 'Server Environment',
    summary: 'استخدام بيئة Linux التي سيعمل عليها الـBackend وفهم الملفات والعمليات والشبكة والسجلات وتشغيل الخدمة على السيرفر.',
    scope: ['Terminal navigation', 'Files & directories', 'Permissions', 'Processes', 'Package managers', 'Environment variables', 'Ports & networking basics', 'Logs', 'systemd basics', 'SSH', 'Reverse proxy concept', 'Nginx basics', 'TLS / HTTPS basics'],
    evidence: 'تشغيل Backend من terminal وإدارة process وenvironment variables وlogs والاتصال بالسيرفر عبر SSH وشرح دور reverse proxy.',
    course: 'https://www.youtube.com/watch?v=ROjZy1WbCIA',
    courseTitle: 'Linux Operating System — Crash Course',
  },
  {
    id: 16,
    title: 'Docker & Docker Compose',
    area: 'Containers',
    summary: 'تغليف التطبيق وخدماته في containers قابلة للتشغيل بنفس الإعدادات محليًا وفي CI وعلى السيرفر.',
    scope: ['Images & containers', 'Docker commands', 'Dockerfile', 'Volumes', 'Networks', 'Docker Compose', 'Registry basics', 'Production image practices'],
    evidence: 'تشغيل NestJS + PostgreSQL + Redis كاملًا باستخدام Docker Compose من أمر واحد.',
    course: 'https://www.youtube.com/watch?v=3c-iBn73dDE',
    courseTitle: 'Docker Full Course — TechWorld with Nana',
  },
  {
    id: 17,
    title: 'CI/CD with GitHub Actions',
    area: 'CI/CD',
    summary: 'تشغيل الاختبارات والبناء وخطوات النشر تلقائيًا مع كل تغيير مناسب في المستودع.',
    scope: ['Actions events', 'Workflows', 'Jobs & steps', 'Runners', 'Secrets', 'Install → test → build', 'Docker image pipeline', 'Deployment gates'],
    evidence: 'GitHub Actions workflow يشغل install/test/build تلقائيًا ويمنع نشر build فاشل.',
    course: 'https://www.youtube.com/watch?v=R8_veQiYBjI',
    courseTitle: 'GitHub Actions CI/CD Tutorial',
  },
  {
    id: 18,
    title: 'AWS Backend Deployment',
    area: 'Cloud',
    summary: 'نشر الـBackend وقاعدة البيانات والخدمات المطلوبة على AWS مع فهم الصلاحيات والشبكة والمراقبة والأسرار.',
    scope: ['IAM', 'EC2', 'S3', 'RDS', 'Networking basics', 'Security Groups', 'Secrets & environment configuration', 'CloudWatch logs & metrics', 'Deployment', 'Health checks', 'Basic backup considerations', 'Operational verification'],
    evidence: 'Backend منشور على AWS مع RDS وhealth endpoint وCloudWatch logs وصلاحيات IAM مناسبة وخطوات نشر موثقة.',
    course: 'https://www.youtube.com/watch?v=YC9ZxTotkxk',
    courseTitle: 'AWS Full Course for Beginners',
    course2: 'https://explore.skillbuilder.aws/learn/courses/134/aws-cloud-practitioner-essentials',
    course2Title: 'AWS Cloud Practitioner Essentials — Official',
  },
  {
    id: 19,
    title: 'SOLID, Clean Code & Refactoring',
    area: 'Code Design',
    summary: 'تحسين جودة الكود وحدود المسؤوليات والاعتماديات بحيث يبقى الـBackend قابلًا للتغيير والاختبار والصيانة.',
    scope: ['Single Responsibility Principle', 'Open/Closed Principle', 'Liskov Substitution Principle', 'Interface Segregation Principle', 'Dependency Inversion Principle', 'Naming & readability', 'Code smells', 'Refactoring decisions'],
    evidence: 'Refactor لخدمة موجودة مع before/after وشرح المشكلة التي عالجها كل تغيير وتأثيره على الاختبار والصيانة.',
    course: 'https://www.youtube.com/watch?v=eHjNjyvZBto',
    courseTitle: 'SOLID Principles with TypeScript',
  },
  {
    id: 20,
    title: 'Clean Architecture',
    area: 'Architecture',
    summary: 'فصل business logic عن framework وقاعدة البيانات وتحديد اتجاه واضح للاعتماديات.',
    scope: ['Domain layer', 'Application / use cases', 'Infrastructure layer', 'Dependency direction', 'Repository abstraction', 'Framework as implementation detail'],
    evidence: 'إعادة تصميم NestJS module واحد بطبقات واضحة مع dependency diagram وrepository abstraction.',
    course: 'https://www.youtube.com/watch?v=UMUJ2-w9LIM',
    courseTitle: 'Clean Architecture with TypeScript — Series',
  },
  {
    id: 21,
    title: 'System Design — Applied Pass',
    area: 'System Design',
    summary: 'إعادة دراسة System Design بعد تطبيق قواعد البيانات وRedis والـQueues والـObservability وDocker وAWS وربط القرارات بحالات استخدام فعلية.',
    scope: ['Caching strategy', 'Queues', 'Database scaling', 'Replication concepts', 'Load balancing', 'Single points of failure', 'Consistency trade-offs', 'Rate limiting', 'Observability', 'Failure handling', 'Designing for scale'],
    evidence: 'System design لنظام Booking أو Notifications مع diagram وكتابة القرارات والـtrade-offs ونقاط الفشل وكيفية مراقبة النظام.',
    course: 'https://www.youtube.com/watch?v=C842vFY5kRo',
    courseTitle: 'System Design Course — Second Pass',
  },
  {
    id: 22,
    title: 'Capstone Production Backend',
    area: 'Capstone',
    summary: 'بناء Backend مستقل بدون tutorial خطوة بخطوة، من تحديد المتطلبات والتصميم حتى الحماية والاختبارات والمراقبة والنشر.',
    scope: ['Requirements & scope', 'ERD & API contract', 'NestJS + Prisma + PostgreSQL', 'JWT & RBAC', 'API hardening', 'Redis', 'BullMQ', 'WebSockets', 'Jest & E2E', 'Structured logging & observability', 'Docker Compose', 'GitHub Actions', 'AWS deployment', 'Health checks', 'Technical documentation'],
    evidence: 'مشروع Backend Production-style منشور فعليًا مع README وarchitecture diagram وAPI documentation واختبارات وCI/CD وsecurity checklist وobservability ونشر AWS قابل للمراجعة.',
  },
];

export const sprintDays: SprintDay[] = [
  {day:1,title:'System Design Overview + JavaScript Intro',phase:'01–02',sessions:['System Design: request flow, databases, scaling & load balancing','JavaScript: variables, types & operators','Conditions, loops & functions','Request-flow diagram + JavaScript exercises']},
  {day:2,title:'JavaScript Core',phase:'02',sessions:['Arrays & methods','Objects & destructuring','Functions, scope & closures','Exercises without returning to the video']},
  {day:3,title:'JavaScript Async + Mini Project',phase:'02',sessions:['Promises & async/await','Error handling + modules + npm','Mini project implementation','Rebuild the project from memory']},
  {day:4,title:'TypeScript Core',phase:'03',sessions:['Types & inference','Interfaces & type aliases','Unions & narrowing','Convert the JavaScript project to TypeScript']},
  {day:5,title:'TypeScript Advanced + Git',phase:'03–04',sessions:['Generics & utility types','Typed async code','Git commits & history','Remote repository + README']},
  {day:6,title:'Git Workflow + Node.js Intro',phase:'04–05',sessions:['Branches, merge & conflicts','Git workflow challenge','Node runtime, modules & npm','Filesystem, env & HTTP basics']},
  {day:7,title:'Node.js Internals',phase:'05',sessions:['Event loop & async model','Events & streams basics','Manual HTTP server','Node exercises from scratch']},
  {day:8,title:'Express + REST APIs',phase:'05',sessions:['Express routes & middleware','Headers, cookies, params, query & status codes','Validation + centralized error handling','Pagination, filtering, sorting + Postman']},
  {day:9,title:'Task Manager API',phase:'06',sessions:['Data model + endpoints','CRUD implementation','Validation + error handling','README + tests + push']},
  {day:10,title:'Store API',phase:'06',sessions:['Products API','Filtering & sorting','Pagination & search','Refactor + Postman + push']},
  {day:11,title:'JWT Authentication',phase:'06',sessions:['Register + password hashing','Login + JWT','Protected routes','Rebuild the auth flow']},
  {day:12,title:'Jobs API',phase:'06',sessions:['Auth + ownership rules','Jobs CRUD','Error handling cleanup','Node/Express review']},
  {day:13,title:'SQL Foundations',phase:'07',sessions:['Tables + constraints','CRUD SQL','WHERE / ORDER / LIMIT','30 manual SQL queries']},
  {day:14,title:'SQL Relationships & Design',phase:'07',sessions:['Primary/foreign keys + relationships','JOINs + GROUP BY','Normalization + Booking ERD','Constraints + migrations concepts']},
  {day:15,title:'PostgreSQL Performance & Transactions',phase:'07',sessions:['Indexes + EXPLAIN basics','Transactions + ACID','Locking + concurrency basics','N+1 + connection pooling + review']},
  {day:16,title:'NestJS Core',phase:'08',sessions:['Modules + controllers','Services + dependency injection','DTOs + ValidationPipe','First CRUD module']},
  {day:17,title:'NestJS + Prisma',phase:'08',sessions:['Prisma schema + migrations','Relations + queries','Config + application structure','Complete resource module']},
  {day:18,title:'Authentication, RBAC & API Security',phase:'08–09',sessions:['Register/login + password hashing','JWT + refresh-token rotation','Guards + roles + permissions + idempotency','CORS + Helmet + rate limiting + OWASP API Top 10']},
  {day:19,title:'NestJS Project — Core Modules',phase:'08',sessions:['Users + auth architecture','Products + categories','Validation + errors','API documentation + review']},
  {day:20,title:'NestJS Project — Orders & Payments',phase:'08–09',sessions:['Cart + orders','Transactions + business rules','Payments flow + authorization checks','Security hardening review + repository cleanup']},
  {day:21,title:'Redis & Caching',phase:'10',sessions:['Redis data types + TTL','Caching patterns','Cache invalidation','Integrate Redis into NestJS']},
  {day:22,title:'Queues & Background Jobs',phase:'11',sessions:['BullMQ architecture','Producer + worker','Retries + delayed jobs','Failure handling + idempotent background job']},
  {day:23,title:'WebSockets & Real-Time',phase:'12',sessions:['NestJS gateway','Socket.IO lifecycle','Rooms + socket auth','Realtime chat/notifications']},
  {day:24,title:'Backend Testing',phase:'13',sessions:['Jest unit tests','Mocks + service tests','Integration tests','E2E with Supertest']},
  {day:25,title:'Observability + Linux Fundamentals',phase:'14–15',sessions:['Structured logging + request IDs','Health checks + metrics + tracing basics','Linux filesystem, permissions & processes','Networking, env, logs, SSH + reverse proxy concepts']},
  {day:26,title:'Docker & Docker Compose',phase:'16',sessions:['Images + containers','Dockerfile','Volumes + networks','NestJS + PostgreSQL + Redis Compose']},
  {day:27,title:'GitHub Actions & CI/CD',phase:'17',sessions:['Workflow structure','Secrets + triggers','Install → test → build pipeline','Deployment gate + verification']},
  {day:28,title:'AWS Backend Deployment',phase:'18',sessions:['IAM + EC2','RDS + S3','Networking + Security Groups + secrets','Deploy + CloudWatch + health checks']},
  {day:29,title:'SOLID + Clean Architecture',phase:'19–20',sessions:['SOLID + clean-code review','Refactor an existing service','Clean Architecture layers','Refactor one NestJS module + diagram']},
  {day:30,title:'System Design + Capstone Planning',phase:'21–22',sessions:['System Design second pass','Design a production system with failure/observability decisions','Capstone scope + ERD + API contract','Create repo, milestones, security/observability checklist']},
];

export const sessionTimes = ['8:00 AM–10:30 AM', '11:00 AM–1:30 PM', '2:30 PM–5:00 PM', '5:30 PM–8:00 PM'];
export const breaks = ['10:30 AM–11:00 AM · Break', '1:30 PM–2:30 PM · Lunch / Prayer', '5:00 PM–5:30 PM · Break'];
