'use client';

import { FormEvent, useEffect, useState } from 'react';
import { motion } from 'framer-motion';
import { ArrowUpRight, Github, Linkedin, Mail, MapPin, Plus, X } from 'lucide-react';
import { Project, supabase } from '../lib/supabase';

const fallback: Project[] = [
  {id:'tnabbah',title:'TNABBAH',subtitle:'Smart Vehicle Diagnostics',description:'Real-vehicle diagnostics, live OBD-II telemetry, intelligent reports, maintenance wallet and a vehicle-aware assistant.',tags:['React Native','FastAPI','MQTT','PostgreSQL'],featured:true,sort_order:1},
  {id:'madad',title:'MADAD',subtitle:'Field Operations Orchestration',description:'Incident management, intelligent dispatch ranking, teams, resources, SLA-aware operations and real-time command dashboards.',tags:['Next.js','Express','Prisma','PostgreSQL'],featured:true,sort_order:2},
  {id:'switchboard',title:'SWITCHBOARD',subtitle:'Visual IT Automation Builder',description:'Drag-and-drop IT workflows backed by a real execution engine for HTTP, databases, PowerShell, SSH, approvals and more.',tags:['Next.js','Node.js','Docker','Automation'],featured:true,sort_order:3},
  {id:'inboxa',title:'INBOXA',subtitle:'Recruitment Inbox Filter',description:'A bilingual recruitment inbox that detects professional opportunities, classifies messages and extracts useful details.',tags:['Next.js','Gmail API','PostgreSQL','OAuth'],sort_order:4},
  {id:'nexus',title:'NEXUS',subtitle:'IT Infrastructure & Operations Center',description:'Enterprise IT lab combining identity, network services, monitoring, assets, security logs, backup and PowerShell automation.',tags:['Windows Server','Active Directory','PowerShell','Monitoring'],sort_order:5},
];

export default function Home(){
 const [projects,setProjects]=useState<Project[]>(fallback); const [open,setOpen]=useState(false); const [admin,setAdmin]=useState(false); const [login,setLogin]=useState(false); const [email,setEmail]=useState(''); const [password,setPassword]=useState('');
 useEffect(()=>{ if(!supabase)return; supabase.from('projects').select('*').order('sort_order').then(({data})=>{if(data?.length)setProjects(data)}); supabase.auth.getSession().then(({data})=>setAdmin(!!data.session)); },[]);
 async function signIn(e:FormEvent){e.preventDefault(); if(!supabase)return alert('Connect Supabase first.'); const {error}=await supabase.auth.signInWithPassword({email,password}); if(error)return alert(error.message); setAdmin(true);setLogin(false)}
 async function addProject(e:FormEvent<HTMLFormElement>){e.preventDefault(); if(!supabase)return alert('Connect Supabase first.'); const f=new FormData(e.currentTarget); const item={title:f.get('title'),subtitle:f.get('subtitle'),description:f.get('description'),image_url:f.get('image_url'),live_url:f.get('live_url'),github_url:f.get('github_url'),tags:String(f.get('tags')||'').split(',').map(x=>x.trim()).filter(Boolean),sort_order:projects.length+1}; const {data,error}=await supabase.from('projects').insert(item).select().single(); if(error)return alert(error.message); setProjects(p=>[...p,data]);setOpen(false)}
 return <main>
  <nav><a className="mark" href="#top">G.</a><div className="navlinks"><a href="#about">ABOUT</a><a href="#hub">OUR HUB</a><a href="#experience">EXPERIENCE</a><a href="#contact">CONTACT</a></div><button className="owner" onClick={()=>admin?setOpen(true):setLogin(true)}>{admin?<><Plus size={14}/> ADD PROJECT</>:'OWNER'}</button></nav>
  <section id="top" className="hero"><div className="kicker">SOFTWARE ENGINEER · FULL-STACK DEVELOPER · PRODUCT BUILDER <span>2026</span></div><motion.h1 initial={{y:60,opacity:0}} animate={{y:0,opacity:1}} transition={{duration:.8}}>PORTFOLIO</motion.h1><div className="heroGrid"><div className="intro"><p className="script">Building systems that</p><h2>CONNECT.<br/>AUTOMATE.<br/>SOLVE.</h2><p>I turn operational problems into real software — from backend systems and connected products to IT automation and infrastructure.</p><div className="signature">Ghala Al-Hashmi Al-Ameer</div><small>SOFTWARE ENGINEER · SAUDI ARABIA</small></div><div className="portrait placeholder"><span>YOUR<br/>PORTRAIT</span></div></div></section>
  <section id="about" className="paper"><div className="sectionTitle"><span>01</span><h3>ABOUT ME</h3></div><div className="aboutGrid"><div className="bigCopy">I BUILD<br/><i>USEFUL</i> THINGS.</div><div><p>Software Engineering graduate focused on backend development, full-stack products, system integration, automation and IT operations.</p><p>My work lives between software and the real world: vehicle telemetry, operational command systems, workflow engines, infrastructure labs and business tools.</p><div className="chips"><span>Backend</span><span>Full-Stack</span><span>Automation</span><span>IT Operations</span><span>Databases</span><span>Deployment</span></div></div></div></section>
  <section id="hub" className="hub"><div className="sectionHead"><div><span>02 / SELECTED SYSTEMS</span><h3>OUR HUB.</h3></div><p>A growing collection of products, experiments and operational systems — built to work, not just to look good.</p></div><div className="projectGrid">{projects.map((p,i)=><motion.article className={'project '+(i<2?'wide':'')} key={p.id} initial={{opacity:0,y:30}} whileInView={{opacity:1,y:0}} viewport={{once:true}}><div className="projectImage">{p.image_url?<img src={p.image_url} alt=""/>:<span>PROJECT VISUAL<br/>PLACEHOLDER</span>}<b>{String(i+1).padStart(2,'0')}</b></div><div className="projectInfo"><div><small>{p.subtitle}</small><h4>{p.title}</h4></div><p>{p.description}</p><div className="tags">{p.tags?.map(t=><span key={t}>{t}</span>)}</div><div className="links">{p.live_url&&<a href={p.live_url} target="_blank">LIVE <ArrowUpRight size={15}/></a>}{p.github_url&&<a href={p.github_url} target="_blank">CODE <Github size={15}/></a>}</div></div></motion.article>)}</div></section>
  <section id="experience" className="paper"><div className="sectionTitle"><span>03</span><h3>EXPERIENCE & TOOLKIT</h3></div><div className="experience"><div><small>PRINCE SULTAN AVIATION ACADEMY</small><h4>Maintenance & Simulators · Software Engineering Trainee</h4><p>Digitized paper-based maintenance workflows, migrated legacy Microsoft Access data into a Dataverse/Power Apps solution, automated operational calculations and delivered a unified interface deployed to the official server.</p></div><div className="toolbox"><span>TypeScript</span><span>JavaScript</span><span>Python</span><span>React / Next.js</span><span>React Native</span><span>Node / Express</span><span>FastAPI</span><span>PostgreSQL</span><span>Supabase</span><span>Docker</span><span>PowerShell</span><span>Windows Server</span></div></div></section>
  <footer id="contact"><div><p className="script">Let's build something useful.</p><h3>GET IN TOUCH.</h3></div><div className="footerLinks"><a href="mailto:ghalaalameer8@gmail.com"><Mail/>EMAIL</a><a href="https://github.com/8llo10" target="_blank"><Github/>GITHUB</a><a href="#"><Linkedin/>LINKEDIN</a><span><MapPin/>MAKKAH · JEDDAH</span></div></footer>
  {(login||open)&&<div className="modalBack"><div className="modal"><button className="close" onClick={()=>{setLogin(false);setOpen(false)}}><X/></button>{login?<form onSubmit={signIn}><small>PRIVATE AREA</small><h3>Owner access</h3><input placeholder="Email" type="email" value={email} onChange={e=>setEmail(e.target.value)} required/><input placeholder="Password" type="password" value={password} onChange={e=>setPassword(e.target.value)} required/><button>ENTER</button></form>:<form onSubmit={addProject}><small>OUR HUB / CMS</small><h3>Add a project</h3><input name="title" placeholder="Project title" required/><input name="subtitle" placeholder="Short subtitle"/><textarea name="description" placeholder="What did you build?" required/><input name="tags" placeholder="Tags, comma, separated"/><input name="image_url" placeholder="Image URL (optional)"/><input name="live_url" placeholder="Live project URL"/><input name="github_url" placeholder="GitHub URL"/><button>PUBLISH PROJECT</button></form>}</div></div>}
 </main>
}
