'use client';

import { FormEvent, useEffect, useState } from 'react';
import { motion } from 'framer-motion';
import { ArrowDownRight, ArrowUpRight, Database, Github, Linkedin, Mail, MapPin, Phone, Plus, ServerCog, Star, Workflow, X } from 'lucide-react';
import { Project, supabase } from '../lib/supabase';

const fallback: Project[] = [
  {id:'tnabbah',title:'TNABBAH',subtitle:'Smart Vehicle Diagnostics',description:'Cross-platform vehicle diagnostics system using ELM327 BLE OBD-II, live ECU telemetry, DTC analysis, MQTT, maintenance workflows and multi-vehicle data.',tags:['React Native','FastAPI','MQTT','PostgreSQL','BLE'],image_url:'/projects/tnabbah.jpg',live_url:'https://tnabbah.vercel.app/',featured:true,sort_order:1},
  {id:'madad',title:'MADAD',subtitle:'Field Resource & Operations Orchestration Platform',description:'Field-operations platform for incident lifecycle management, team and resource allocation, optimization-based dispatch, RBAC, realtime tracking and SLA monitoring.',tags:['Next.js','Express','Prisma','PostgreSQL','Realtime'],image_url:'/projects/madad.jpg',live_url:'https://madad-hajj-field-resource-operation.vercel.app',featured:true,sort_order:2},
  {id:'switchboard',title:'SWITCHBOARD',subtitle:'Visual IT Automation Builder',description:'Visual workflow builder for IT operations with an execution-engine architecture covering HTTP, databases, PowerShell, SSH, conditions, approvals and scheduled triggers.',tags:['Next.js','Node.js','PostgreSQL','Docker','Automation'],image_url:'/projects/switchboard.jpg',featured:true,sort_order:3},
  {id:'hiremail',title:'HireMail AI',subtitle:'Recruitment Email Classification & Tracking',description:'Gmail-integrated system that classifies recruitment emails and organizes interviews, offers, assessments and career opportunities in a structured dashboard.',tags:['Next.js','Gmail API','OAuth','PostgreSQL'],image_url:'/projects/hiremail.jpg',live_url:'https://hiremail-ai-v2-omega.vercel.app',sort_order:4},
  {id:'proof',title:'PROOF',subtitle:'Decision Evidence Registry',description:'Decision-record system for property and contractor workflows, storing parties, approvals, evidence and status as traceable records.',tags:['Full-Stack','Workflow','Audit Trail','Decision Records'],image_url:'/projects/proof.jpg',live_url:'https://proof-verifiable-decision-platform.vercel.app/',sort_order:5},
];
const stack=['TypeScript','JavaScript','Python','React','Next.js','React Native','Node.js','Express','FastAPI','REST APIs','PostgreSQL','Supabase','Prisma','Docker','MQTT','OAuth','GitHub','Vercel'];
const commandCenter='https://project-command-center-l6qiq2x08-ghala-alameer-s-projects.vercel.app';
const technicalServices='https://emspsaa.com/';

function ProjectVisual({project}:{project:Project}){const [failed,setFailed]=useState(false);return <div className="posterVisual">{project.image_url&&!failed?<img src={project.image_url} alt={`${project.title} interface`} onError={()=>setFailed(true)}/>:<><div className="fakeWindow"><i/><i/><i/></div><span>PROJECT PREVIEW</span></>}</div>}
function BrandMark(){const [failed,setFailed]=useState(false);return <>{!failed?<img className="brandLogo" src="/images/logo.png" alt="GA" onError={()=>setFailed(true)}/>:<span>G.</span>}</>}
function TechnicalVisual(){return <div className="techArt" aria-label="Animated software system architecture"><div className="techGrid"/><div className="terminal"><div className="terminalTop"><i/><i/><i/></div><code><span>POST</span> /api/workflows</code><code><span>GET</span> /systems/status</code><code>db.connect()</code><code>event → process → persist</code></div><div className="systemMap"><span className="flowLine l1"/><span className="flowLine l2"/><span className="flowLine l3"/><div className="node client">CLIENT</div><div className="node api">API</div><div className="node service">SERVICE</div><div className="node db"><Database size={18}/><b>DB</b></div><i className="pulse p1"/><i className="pulse p2"/><i className="pulse p3"/></div><div className="techLabel">SYSTEM / FLOW / DATA</div></div>}

export default function Home(){
 const [projects,setProjects]=useState<Project[]>(fallback);const [open,setOpen]=useState(false);const [admin,setAdmin]=useState(false);const [login,setLogin]=useState(false);const [email,setEmail]=useState('');const [password,setPassword]=useState('');
 useEffect(()=>{if(!supabase)return;supabase.from('projects').select('*').order('sort_order').then(({data})=>{if(data?.length)setProjects(data)});supabase.auth.getSession().then(({data})=>setAdmin(!!data.session))},[]);
 async function signIn(e:FormEvent){e.preventDefault();if(!supabase)return alert('Connect Supabase first.');const {error}=await supabase.auth.signInWithPassword({email,password});if(error)return alert(error.message);setAdmin(true);setLogin(false)}
 async function addProject(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!supabase)return alert('Connect Supabase first.');const f=new FormData(e.currentTarget);const item={title:f.get('title'),subtitle:f.get('subtitle'),description:f.get('description'),image_url:f.get('image_url'),live_url:f.get('live_url'),github_url:f.get('github_url'),tags:String(f.get('tags')||'').split(',').map(x=>x.trim()).filter(Boolean),sort_order:projects.length+1};const {data,error}=await supabase.from('projects').insert(item).select().single();if(error)return alert(error.message);setProjects(p=>[...p,data]);setOpen(false)}
 return <main>
  <nav><a className="mark logoMark" href="#top"><BrandMark/></a><div className="navlinks"><a href="#about">PROFILE</a><a href="#hub">PROJECTS</a><a href="#proof">ENGINEERING</a><a href="#experience">EXPERIENCE</a><a href="#contact">CONTACT</a></div><button className="owner" onClick={()=>admin?setOpen(true):setLogin(true)}>{admin?<><Plus size={14}/> ADD PROJECT</>:'OWNER'}</button></nav>
  <section id="top" className="hero"><div className="dotField"/><div className="orb orb1"/><div className="orb orb2"/><div className="topline"><span>GHALA AL-HASHMI AL-AMEER</span><span>SOFTWARE ENGINEERING · 2026</span></div><motion.div className="heroTitle" initial={{opacity:0,y:45}} animate={{opacity:1,y:0}} transition={{duration:.8}}><span>PORT</span><span>FOLIO</span></motion.div><div className="heroCollage"><motion.div className="introCard stickerCard" initial={{rotate:-3,opacity:0}} animate={{rotate:-1,opacity:1}}><span className="tape tapeA"/><p className="eyebrow">SOFTWARE ENGINEER</p><h1>GHALA<br/><i>AL-HASHMI</i></h1><p className="introText">B.Sc. Software Engineering graduate focused on backend development, full-stack systems and IT automation.</p></motion.div><motion.div className="portraitFrame techFrame" initial={{scale:.96,opacity:0}} animate={{scale:1,opacity:1}}><TechnicalVisual/><div className="photoTag">MAKKAH · JEDDAH</div></motion.div><div className="heroSide"><div className="miniCard"><b>CORE AREAS</b><small>BACKEND · APIs · DATABASES · INTEGRATIONS</small></div><div className="yearBadge"><span>GRAD.</span><strong>2026</strong><span>UQU</span></div></div><div className="scrollHint"><ArrowDownRight/> SELECTED WORK BELOW</div></div></section>
  <section id="about" className="about paperTexture"><div className="sectionStamp">01 / PROFILE</div><div className="aboutPoster"><div className="aboutLeft"><p className="eyebrow">PROFILE</p><h2>GHALA<br/><span>AL-HASHMI</span></h2><div className="quoteBox">Software Engineer · Backend & Full-Stack</div></div><div className="aboutRight"><div className="infoBox"><span>EDUCATION</span><b>B.Sc. Software Engineering — Umm Al-Qura University, 2026</b></div><div className="infoBox"><span>BASE</span><b>Makkah · Jeddah, Saudi Arabia</b></div><div className="infoBox"><span>FOCUS</span><b>Backend Systems · APIs · Databases · Integrations · Automation</b></div><div className="infoBox"><span>EXPERIENCE</span><b>Software engineering training in aviation maintenance systems</b></div><div className="infoBox"><span>STATUS</span><b>Open to Software Engineering · Backend · Full-Stack opportunities</b></div></div></div></section>
  <section className="skillsBand"><div className="marquee">{[...stack,...stack].map((s,i)=><span key={i}>{s}<Star size={10} fill="currentColor"/></span>)}</div></section>
  <section id="hub" className="hub"><div className="hubHeader"><div><span className="sectionStamp light">02 / PROJECTS</span><h2>SELECTED <i>WORK</i></h2></div><div><p>Systems covering vehicle diagnostics, field operations, IT automation, email processing and decision records.</p><a className="progressLink" href={commandCenter} target="_blank">PROJECT COMMAND CENTER <ArrowUpRight size={15}/></a></div></div><div className="projectMasonry">{projects.map((p,i)=><motion.article key={p.id} className={`projectPoster poster${(i%5)+1}`} initial={{opacity:0,y:45,rotate:i%2?2:-2}} whileInView={{opacity:1,y:0,rotate:i%2?1:-1}} viewport={{once:true,amount:.2}}><div className="posterNumber">{String(i+1).padStart(2,'0')}</div><ProjectVisual project={p}/><div className="posterCopy"><small>{p.subtitle}</small><h3>{p.title}</h3><p>{p.description}</p><div className="tags">{p.tags?.map(t=><span key={t}>{t}</span>)}</div><div className="links">{p.live_url&&<a href={p.live_url} target="_blank">LIVE <ArrowUpRight size={14}/></a>}{p.github_url&&<a href={p.github_url} target="_blank">GITHUB <Github size={14}/></a>}</div></div><div className="pin">✦</div></motion.article>)}</div></section>
  <section id="proof" className="experienceSection paperTexture"><span className="sectionStamp">03 / ENGINEERING</span><div className="experienceGrid"><div className="experienceMain"><h2>ENGINEERING<br/><i>WORKFLOW.</i></h2><div className="timeline"><span className="line"/><div className="timelineItem"><b>01 · SYSTEM DESIGN</b><small>ERD · entities · permissions · states</small><p>Define the data model, relationships, roles, constraints and state transitions before implementation.</p></div><div className="timelineItem proofItem"><b>02 · BACKEND</b><small>REST APIs · authentication · validation · business logic</small><p>Implement service and data-access layers with explicit validation, authorization and integration boundaries.</p></div><div className="timelineItem proofItem"><b>03 · INTEGRATION</b><small>MQTT · BLE · OAuth · realtime · external services</small><p>Connect applications to devices, event streams and third-party services when required by the system.</p></div><div className="timelineItem proofItem"><b>04 · DEPLOYMENT</b><small>Docker · VPS · cloud platforms · logs</small><p>Configure deployment, environment variables, database connectivity and runtime monitoring.</p></div></div></div><div className="toolPoster"><span className="tape tapeB"/><p className="eyebrow">TECHNICAL SCOPE</p><div className="proofIcons"><ServerCog/><Database/><Workflow/></div><div className="toolCloud"><span>CLIENT</span><span>REST API</span><span>AUTH</span><span>BUSINESS LOGIC</span><span>POSTGRESQL</span><span>REALTIME</span><span>DEPLOYMENT</span></div></div></div></section>
  <section id="experience" className="experienceSection paperTexture"><span className="sectionStamp">04 / EXPERIENCE</span><div className="experienceGrid"><div className="experienceMain"><h2>PRINCE SULTAN<br/><i>AVIATION ACADEMY.</i></h2><div className="timeline"><span className="line"/><div className="timelineItem"><b>SOFTWARE ENGINEERING TRAINEE</b><small>Maintenance & Simulators · Technical Services</small><p>Digitized paper-based maintenance workflows, migrated legacy Microsoft Access data to Power Apps and Dataverse, automated operational calculations, and contributed to a unified interface deployed on the official server.</p><a className="progressLink dark" href={technicalServices} target="_blank">TECHNICAL SERVICES DEPARTMENT <ArrowUpRight size={15}/></a></div></div></div><div className="toolPoster"><span className="tape tapeB"/><p className="eyebrow">WORK DELIVERED</p><div className="toolCloud"><span>WORKFLOW DIGITIZATION</span><span>ACCESS DATA MIGRATION</span><span>POWER APPS</span><span>DATAVERSE</span><span>OPERATIONAL CALCULATIONS</span><span>INTERNAL WEB SYSTEM</span></div></div></div></section>
  <footer id="contact"><div className="footerStar">✦</div><div><p className="script">CONTACT</p><h2>GHALA<br/>AL-HASHMI</h2></div><div className="footerLinks"><a href="mailto:ghalaalameer8@gmail.com"><Mail/>ghalaalameer8@gmail.com</a><a href="tel:+966560602239"><Phone/>+966 56 060 2239</a><a href="https://github.com/8llo10" target="_blank"><Github/>github.com/8llo10</a><a href="https://www.linkedin.com/in/ghala-abdullah-alameer-541733373" target="_blank"><Linkedin/>LINKEDIN</a><span><MapPin/>MAKKAH · JEDDAH · SAUDI ARABIA</span></div></footer>
  {(login||open)&&<div className="modalBack"><div className="modal"><button className="close" onClick={()=>{setLogin(false);setOpen(false)}}><X/></button>{login?<form onSubmit={signIn}><small>PRIVATE AREA</small><h3>Owner access</h3><input placeholder="Email" type="email" value={email} onChange={e=>setEmail(e.target.value)} required/><input placeholder="Password" type="password" value={password} onChange={e=>setPassword(e.target.value)} required/><button>ENTER</button></form>:<form onSubmit={addProject}><small>PROJECTS / CMS</small><h3>Add a project</h3><input name="title" placeholder="Project title" required/><input name="subtitle" placeholder="Short subtitle"/><textarea name="description" placeholder="What did you build?" required/><input name="tags" placeholder="Tags, comma, separated"/><input name="image_url" placeholder="Image URL (optional)"/><input name="live_url" placeholder="Live project URL"/><input name="github_url" placeholder="GitHub URL"/><button>PUBLISH PROJECT</button></form>}</div></div>}
  <style jsx global>{`
   .logoMark{width:48px;height:38px;display:grid;place-items:start center;overflow:hidden}.brandLogo{width:48px;height:38px;object-fit:contain;object-position:left center}.techFrame{min-width:0}.techArt{height:380px;position:relative;overflow:hidden;border:1px solid var(--ink);background:linear-gradient(145deg,#e3b7aa,#b95767 52%,#68253f);clip-path:polygon(5% 0,100% 2%,97% 96%,0 100%);color:#fff7e9;isolation:isolate}.techGrid{position:absolute;inset:0;background-image:linear-gradient(#fff2 1px,transparent 1px),linear-gradient(90deg,#fff2 1px,transparent 1px);background-size:28px 28px;mask-image:linear-gradient(135deg,#000,transparent 82%)}.terminal{position:absolute;left:8%;top:10%;width:54%;padding:12px;background:#2e1714e8;border:1px solid #fff6;box-shadow:9px 10px 0 #35141638;transform:rotate(-2deg);display:grid;gap:7px}.terminalTop{height:12px;border-bottom:1px solid #fff3;margin-bottom:4px}.terminalTop i{display:inline-block;width:5px;height:5px;border:1px solid #f6e5d5;border-radius:50%;margin-right:4px}.terminal code{font:7px 'DM Mono';color:#f6dfd5;white-space:nowrap}.terminal code span{color:#f3ce70}.systemMap{position:absolute;inset:42% 7% 9%}.node{position:absolute;z-index:3;border:1px solid #fff9;background:#f7ead8e8;color:#421d18;padding:8px 10px;font:600 7px 'DM Mono';letter-spacing:.1em;box-shadow:3px 3px 0 #35141655}.node.client{left:2%;top:24%}.node.api{left:38%;top:3%}.node.service{right:2%;top:28%}.node.db{left:42%;bottom:1%;display:flex;align-items:center;gap:5px}.node.db svg{width:14px;height:14px}.flowLine{position:absolute;height:1px;background:#fff9;transform-origin:left center;z-index:1}.l1{width:43%;left:13%;top:38%;transform:rotate(-18deg)}.l2{width:38%;left:48%;top:21%;transform:rotate(20deg)}.l3{width:31%;left:48%;top:32%;transform:rotate(75deg)}.pulse{position:absolute;z-index:4;width:8px;height:8px;border-radius:50%;background:#f3ce70;box-shadow:0 0 0 0 #f3ce7088;animation:techPulse 2.2s ease-out infinite}.p1{left:35%;top:25%}.p2{right:24%;top:34%;animation-delay:.7s}.p3{left:48%;bottom:21%;animation-delay:1.4s}.techLabel{position:absolute;right:8%;top:9%;font:7px 'DM Mono';letter-spacing:.18em;writing-mode:vertical-rl;opacity:.8}@keyframes techPulse{0%{box-shadow:0 0 0 0 #f3ce70aa;transform:scale(.8)}65%{box-shadow:0 0 0 11px #f3ce7000;transform:scale(1.15)}100%{box-shadow:0 0 0 0 #f3ce7000;transform:scale(.8)}}
   @media(max-width:640px){.logoMark{width:44px;height:34px}.brandLogo{width:44px;height:34px}.techArt{height:min(72vw,290px);clip-path:polygon(3% 0,100% 1%,98% 98%,0 100%)}.terminal{left:7%;top:9%;width:58%;padding:9px}.terminal code{font-size:6px}.systemMap{inset:43% 5% 8%}.node{font-size:6px;padding:6px 7px}.node.db svg{width:12px;height:12px}.techLabel{font-size:6px}.photoTag{bottom:10px}}
   @media(max-width:390px){.techArt{height:68vw}.terminal{width:62%}.terminal code:nth-of-type(4){display:none}}
   @media(prefers-reduced-motion:reduce){.pulse{animation:none}}
  `}</style>
 </main>
}
