'use client';

import { FormEvent, useEffect, useState } from 'react';
import { motion } from 'framer-motion';
import { ArrowDownRight, ArrowDownToLine, ArrowUpRight, Database, Github, Linkedin, Mail, MapPin, Phone, Plus, ServerCog, Star, Workflow, X } from 'lucide-react';
import { Project, supabase } from '../lib/supabase';

const fallback: Project[] = [
  {id:'tnabbah',title:'TNABBAH',subtitle:'Smart Vehicle Diagnostics',description:'Real-vehicle diagnostics with BLE OBD-II, live telemetry, DTC analysis, maintenance workflows and multi-vehicle support.',tags:['React Native','FastAPI','MQTT','PostgreSQL','BLE'],image_url:'/projects/tnabbah.jpg',live_url:'https://tnabbah.vercel.app/',featured:true,sort_order:1},
  {id:'madad',title:'MADAD',subtitle:'Field Resource & Operations Orchestration Platform',description:'Field operations platform for incidents, dispatch, teams, resources, RBAC, realtime tracking and SLA monitoring.',tags:['Next.js','Express','Prisma','PostgreSQL','Realtime'],image_url:'/projects/madad.jpg',live_url:'https://madad-hajj-field-resource-operation.vercel.app',featured:true,sort_order:2},
  {id:'switchboard',title:'SWITCHBOARD',subtitle:'Visual IT Automation Builder',description:'Visual IT automation builder with executable workflows, conditions, approvals, scheduled triggers and infrastructure actions.',tags:['Next.js','Node.js','PostgreSQL','Docker','Automation'],image_url:'/projects/switchboard.jpg',featured:true,sort_order:3},
  {id:'hiremail',title:'HireMail AI',subtitle:'Recruitment Email Classification & Tracking',description:'Gmail-integrated platform that classifies career emails and tracks interviews, offers and assessments.',tags:['Next.js','Gmail API','OAuth','PostgreSQL'],image_url:'/projects/hiremail.jpg',live_url:'https://hiremail-ai-v2-omega.vercel.app',sort_order:4},
  {id:'proof',title:'PROOF',subtitle:'Decision Evidence Registry',description:'Traceable decision records for approvals, evidence, parties and workflow status.',tags:['Full-Stack','Workflow','Audit Trail','Decision Records'],image_url:'/projects/proof.jpg',live_url:'https://proof-verifiable-decision-platform.vercel.app/',sort_order:5},
];

const stack=['TypeScript','JavaScript','Python','React','Next.js','React Native','Node.js','Express','FastAPI','REST APIs','Clean Architecture','Supabase','Prisma','Docker','MQTT','OAuth','GitHub','Vercel'];
const commandCenter='https://project-command-center-l6qiq2x08-ghala-alameer-s-projects.vercel.app';
const technicalServices='https://emspsaa.com/';
const resumeFile='/Ghala-Al-Hashmi-Al-Ameer-CV-2026.pdf';
const reveal={initial:{opacity:0,y:28},whileInView:{opacity:1,y:0},viewport:{once:true,amount:.18},transition:{duration:.55,ease:'easeOut' as const}};

function ProjectVisual({project}:{project:Project}){const [failed,setFailed]=useState(false);return <div className="posterVisual">{project.image_url&&!failed?<img src={project.image_url} alt={`${project.title} interface`} onError={()=>setFailed(true)}/>:<><div className="fakeWindow"><i/><i/><i/></div><span>PROJECT PREVIEW</span></>}</div>}
function BrandMark(){const [failed,setFailed]=useState(false);return <>{!failed?<img className="brandLogo" src="/images/logo.png" alt="GA" onError={()=>setFailed(true)}/>:<span>G.</span>}</>}
function HeroVisual(){const [failed,setFailed]=useState(false);return <div className="heroImageBox">{!failed?<img src="/images/hero.jpg" alt="Portfolio visual" onError={()=>setFailed(true)}/>:<div className="heroImagePlaceholder"><span>HERO IMAGE</span><small>public/images/hero.jpg</small></div>}</div>}

export default function Home(){
  const [projects,setProjects]=useState<Project[]>(fallback);const [open,setOpen]=useState(false);const [admin,setAdmin]=useState(false);const [login,setLogin]=useState(false);const [email,setEmail]=useState('');const [password,setPassword]=useState('');
  useEffect(()=>{if(!supabase)return;supabase.from('projects').select('*').order('sort_order').then(({data})=>{if(data?.length)setProjects(data)});supabase.auth.getSession().then(({data})=>setAdmin(!!data.session))},[]);
  async function signIn(e:FormEvent){e.preventDefault();if(!supabase)return alert('Connect Supabase first.');const {error}=await supabase.auth.signInWithPassword({email,password});if(error)return alert(error.message);setAdmin(true);setLogin(false)}
  async function addProject(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!supabase)return alert('Connect Supabase first.');const f=new FormData(e.currentTarget);const item={title:f.get('title'),subtitle:f.get('subtitle'),description:f.get('description'),image_url:f.get('image_url'),live_url:f.get('live_url'),github_url:f.get('github_url'),tags:String(f.get('tags')||'').split(',').map(x=>x.trim()).filter(Boolean),sort_order:projects.length+1};const {data,error}=await supabase.from('projects').insert(item).select().single();if(error)return alert(error.message);setProjects(p=>[...p,data]);setOpen(false)}

  return <main>
    <nav><a className="mark logoMark" href="#top"><BrandMark/></a><div className="navlinks"><a href="#about">PROFILE</a><a href="#hub">PROJECTS</a><a href="#proof">ENGINEERING</a><a href="#experience">EXPERIENCE</a><a href="#resume">RESUME</a><a href="#contact">CONTACT</a></div><button className="owner" onClick={()=>admin?setOpen(true):setLogin(true)}>{admin?<><Plus size={14}/> ADD PROJECT</>:'OWNER'}</button></nav>

    <section id="top" className="hero"><div className="dotField"/><div className="topline"><span>GHALA AL-AMEER</span><span>BACKEND · FULL-STACK · SYSTEMS</span></div><motion.div className="heroTitle" initial={{opacity:0,y:45}} animate={{opacity:1,y:0}} transition={{duration:.8}}><span>PORT</span><span>FOLIO</span></motion.div><div className="heroCollage heroCollageClean"><motion.div className="introCard stickerCard" initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} transition={{duration:.55}}><p className="eyebrow">SOFTWARE ENGINEER</p><h1>GHALA<br/><i>AL-AMEER</i></h1><p className="introText">Software Engineer focused on backend systems, APIs, clean architecture, integrations and full-stack development.</p></motion.div><motion.div className="heroImageWrap" initial={{opacity:0,y:18,scale:.98}} animate={{opacity:1,y:0,scale:1}} transition={{delay:.08,duration:.55}}><HeroVisual/></motion.div><div className="scrollHint"><ArrowDownRight/> SELECTED WORK BELOW</div></div></section>

    <section id="about" className="about paperTexture"><div className="sectionStamp">01 / PROFILE</div><motion.div className="aboutPoster" {...reveal}><div className="aboutLeft"><p className="eyebrow">PROFILE</p><h2>GHALA<br/><span>AL-AMEER</span></h2><div className="quoteBox">Software Engineer · Backend & Full-Stack</div></div><div className="aboutRight"><div className="infoBox"><span>EDUCATION</span><b>B.Sc. Software Engineering — Umm Al-Qura University, 2026</b></div><div className="infoBox"><span>BASE</span><b>Makkah · Jeddah, Saudi Arabia</b></div><div className="infoBox"><span>FOCUS</span><b>Backend Systems · APIs · Clean Architecture · Integrations · Automation</b></div><div className="infoBox"><span>EXPERIENCE</span><b>Aviation maintenance systems · Legacy modernization · Operational software</b></div><div className="infoBox"><span>STATUS</span><b>Open to Software Engineering · Backend · Full-Stack opportunities</b></div></div></motion.div></section>

    <section className="skillsBand"><div className="marquee">{[...stack,...stack].map((s,i)=><span key={i}>{s}<Star size={10} fill="currentColor"/></span>)}</div></section>

    <section id="hub" className="hub"><motion.div className="hubHeader" {...reveal}><div><span className="sectionStamp light">02 / PROJECTS</span><h2>SELECTED <i>WORK</i></h2></div><div><p>Selected systems across backend, automation, realtime services and operational software.</p><a className="progressLink" href={commandCenter} target="_blank">PROJECT COMMAND CENTER <ArrowUpRight size={15}/></a></div></motion.div><div className="projectMasonry">{projects.map((p,i)=><motion.article key={p.id} className={`projectPoster poster${(i%5)+1}`} initial={{opacity:0,y:34,rotate:i%2?1.2:-1.2}} whileInView={{opacity:1,y:0,rotate:0}} whileHover={{y:-6}} viewport={{once:true,amount:.18}} transition={{duration:.5,delay:Math.min(i*.05,.2)}} role={(p.live_url||p.github_url)?'link':undefined} tabIndex={(p.live_url||p.github_url)?0:undefined} onClick={(e)=>{if((e.target as HTMLElement).closest('a'))return;const url=p.live_url||p.github_url;if(url)window.open(url,'_blank','noopener,noreferrer')}} onKeyDown={(e)=>{if((e.key==='Enter'||e.key===' ')&&(p.live_url||p.github_url))window.open(p.live_url||p.github_url,'_blank','noopener,noreferrer')}}><div className="posterNumber">{String(i+1).padStart(2,'0')}</div><ProjectVisual project={p}/><div className="posterCopy"><small>{p.subtitle}</small><h3>{p.title}</h3><p>{p.description}</p><div className="tags">{p.tags?.map(t=><span key={t}>{t}</span>)}</div><div className="links">{p.live_url&&<a href={p.live_url} target="_blank">LIVE <ArrowUpRight size={14}/></a>}{p.github_url&&<a href={p.github_url} target="_blank">GITHUB <Github size={14}/></a>}</div></div></motion.article>)}</div></section>

    <section id="proof" className="experienceSection paperTexture"><span className="sectionStamp">03 / ENGINEERING</span><motion.div className="experienceGrid" {...reveal}><div className="experienceMain"><h2>ENGINEERING<br/><i>WORKFLOW.</i></h2><div className="timeline"><span className="line"/><div className="timelineItem"><b>01 · SYSTEM DESIGN</b><small>ERD · entities · permissions · states</small><p>Model the system, roles and state transitions before implementation.</p></div><div className="timelineItem proofItem"><b>02 · CLEAN ARCHITECTURE</b><small>domain · services · interfaces · infrastructure</small><p>Separate business rules from frameworks, integrations and data access.</p></div><div className="timelineItem proofItem"><b>03 · INTEGRATION</b><small>MQTT · BLE · OAuth · realtime</small><p>Connect devices, event streams and external services through clear boundaries.</p></div><div className="timelineItem proofItem"><b>04 · DEPLOYMENT</b><small>Docker · VPS · cloud · logs</small><p>Ship, configure and monitor production-ready systems.</p></div></div></div><div className="toolPoster"><p className="eyebrow">TECHNICAL SCOPE</p><div className="proofIcons"><ServerCog/><Database/><Workflow/></div><div className="toolCloud"><span>CLIENT</span><span>REST API</span><span>AUTH</span><span>CLEAN ARCHITECTURE</span><span>POSTGRESQL</span><span>REALTIME</span><span>DEPLOYMENT</span></div></div></motion.div></section>

    <section id="experience" className="experienceSection paperTexture"><span className="sectionStamp">04 / EXPERIENCE</span><motion.div className="experienceGrid" {...reveal}><div className="experienceMain"><h2>PRINCE SULTAN<br/><i>AVIATION ACADEMY.</i></h2><div className="timeline"><span className="line"/><div className="timelineItem"><b>SOFTWARE ENGINEERING TRAINEE</b><small>Maintenance & Simulators · Technical Services</small><p>Modernized legacy workflows, migrated Access data to Dataverse, digitized maintenance processes and delivered operational systems to the official server.</p><a className="progressLink dark" href={technicalServices} target="_blank">TECHNICAL SERVICES DEPARTMENT <ArrowUpRight size={15}/></a></div></div></div><div className="toolPoster"><p className="eyebrow">WORK DELIVERED</p><div className="toolCloud"><span>WORKFLOW DIGITIZATION</span><span>LEGACY MODERNIZATION</span><span>POWER APPS</span><span>DATAVERSE</span><span>OPERATIONAL SYSTEMS</span><span>PRODUCTION DELIVERY</span></div></div></motion.div></section>

    <section id="resume" className="resumeSection"><motion.div className="resumeInner" {...reveal}><div><span className="sectionStamp">05 / RESUME</span><p className="resumeKicker">CURRICULUM VITAE</p><h2>RESUME</h2><p className="resumeMeta">Latest version · Updated 2026</p></div><a className="resumeDownload" href={resumeFile} download><span>DOWNLOAD CV</span><ArrowDownToLine size={18}/></a></motion.div></section>

    <footer id="contact"><motion.div className="footerStar" initial={{opacity:0,rotate:-20}} whileInView={{opacity:1,rotate:0}} viewport={{once:true}}>✦</motion.div><motion.div {...reveal}><p className="script">CONTACT</p><h2>GHALA<br/>AL-AMEER</h2></motion.div><motion.div className="footerLinks" {...reveal}><a href="mailto:ghalaalameer8@gmail.com"><Mail/>ghalaalameer8@gmail.com</a><a href="tel:+966560602239"><Phone/>+966 56 060 2239</a><a href="https://github.com/8llo10" target="_blank"><Github/>github.com/8llo10</a><a href="https://www.linkedin.com/in/ghala-abdullah-alameer-541733373" target="_blank"><Linkedin/>LINKEDIN</a><span><MapPin/>MAKKAH · JEDDAH · SAUDI ARABIA</span></motion.div></footer>

    {(login||open)&&<div className="modalBack"><div className="modal"><button className="close" onClick={()=>{setLogin(false);setOpen(false)}}><X/></button>{login?<form onSubmit={signIn}><small>PRIVATE AREA</small><h3>Owner access</h3><input placeholder="Email" type="email" value={email} onChange={e=>setEmail(e.target.value)} required/><input placeholder="Password" type="password" value={password} onChange={e=>setPassword(e.target.value)} required/><button>ENTER</button></form>:<form onSubmit={addProject}><small>PROJECTS / CMS</small><h3>Add a project</h3><input name="title" placeholder="Project title" required/><input name="subtitle" placeholder="Short subtitle"/><textarea name="description" placeholder="What did you build?" required/><input name="tags" placeholder="Tags, comma, separated"/><input name="image_url" placeholder="Image URL (optional)"/><input name="live_url" placeholder="Live project URL"/><input name="github_url" placeholder="GitHub URL"/><button>PUBLISH PROJECT</button></form>}</div></div>}
  </main>;
}
