-- Run this once in Supabase → SQL Editor.
-- The website uses the service-role key only on the server, so no public table policies are required.

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  title text not null,
  subtitle text default '',
  description text not null,
  image_url text default '',
  project_url text default '',
  github_url text default '',
  tags jsonb not null default '[]'::jsonb,
  featured boolean not null default true,
  sort_order integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.sections (
  id bigint generated by default as identity primary key,
  key text unique not null,
  type text not null,
  title text not null,
  eyebrow text default '',
  body text default '',
  image_url text default '',
  layout text not null default 'bento',
  sort_order integer not null default 1,
  enabled boolean not null default true,
  config jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.site_settings (
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

insert into storage.buckets (id, name, public)
values ('portfolio-images', 'portfolio-images', true)
on conflict (id) do update set public = true;

-- Seed page sections. Safe to run more than once.
insert into public.sections (key,type,title,eyebrow,body,image_url,layout,sort_order,enabled,config) values
('hero','hero','I build systems that turn complex ideas into useful products.','SOFTWARE ENGINEER','From backend architecture and databases to interfaces, integrations and deployment — I like owning the full path from problem to working system.','','split',1,true,'{"imageHint":"YOUR PHOTO — portrait/editorial cutout · recommended 4:5"}'),
('projects','projects','Selected Projects','FEATURED WORK','Real systems, integrations and products built around practical problems.','','grid',2,true,'{}'),
('about','about','More than just code.','ABOUT','I’m a Software Engineer who enjoys backend systems, databases, product thinking, integrations and solving operational problems. I care about clean execution, not just ideas.','','bento',3,true,'{"imageHint":"ABOUT PHOTO — candid/workspace photo · recommended 4:3"}'),
('experience','experience','Experience','SELECTED EXPERIENCE','Prince Sultan Aviation Academy — technical training in an operational environment involving maintenance and simulator workflows.','','editorial',4,true,'{}'),
('skills','skills','Tools I use to build end-to-end systems','STACK','JavaScript · TypeScript · Python · Java · React · Next.js · React Native · FastAPI · PostgreSQL · MySQL · Supabase · Firebase · MQTT · Git · Linux · Windows Server · Active Directory · TCP/IP · DNS · DHCP','','bento',5,true,'{}'),
('contact','contact','Have a problem worth solving?','LET’S TALK','I’m open to software engineering, backend, full-stack and technical operations opportunities.','','full',6,true,'{}')
on conflict (key) do nothing;

insert into public.projects (slug,title,subtitle,description,image_url,project_url,github_url,tags,featured,sort_order) values
('madad','مَدَد | MADAD','Field Resource & Operations Orchestration','Enterprise operations platform for field incidents, teams, equipment, resources, dispatch and command-center workflows.','','','', '["Next.js","Backend","PostgreSQL","Operations"]',true,1),
('tnabbah','TNABBAH','Smart Vehicle Diagnostics','Real-time vehicle diagnostics using OBD-II, MQTT, mobile interfaces and backend services.','','','', '["React Native","FastAPI","MQTT","Supabase"]',true,2),
('wasl','وَصْل | WASL','IT Help Desk & Asset Management','Support tickets, users, devices, priorities, ownership and asset lifecycle management for IT teams.','','','', '["IT Support","Assets","RBAC","PostgreSQL"]',true,3),
('hiremail','HireMail','Professional Inbox Workspace','A productivity platform for organizing and prioritizing professional email and opportunities.','','','', '["Next.js","OAuth","Gmail API","Productivity"]',true,4)
on conflict (slug) do nothing;

insert into public.site_settings (key,value) values
('main', '{"name":"Ghala AlHashmi Alameer","role":"Software Engineer · Full-Stack & Systems","location":"Makkah, Saudi Arabia","email":"YOUR_EMAIL","linkedin_url":"YOUR_LINKEDIN_URL","github_url":"https://github.com/8llo10","cv_url":"/Ghala_AlHashmi_Alameer_CV.pdf","availability":"Open to software engineering & IT opportunities"}')
on conflict (key) do nothing;
